CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(20) NOT NULL UNIQUE,
    password varchar NOT NULL,
    role varchar(20) NOT NULL
);

CREATE TABLE Musician (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    members varchar(100)
);

CREATE TABLE Product(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    type varchar(20) NOT NULL,
    genre varchar(40) NOT NULL ,
    year int CHECK ( year > 1900 ) NOT NULL,
    price float4 NOT NULL,
    description varchar(70) default 'Отсутствует',
    musician_id int REFERENCES Musician(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE orders (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     completed boolean DEFAULT false,
     price float4 DEFAULT 0 NOT NULL,
     person_id int REFERENCES Person(id) ON DELETE SET NULL
);

CREATE TABLE Product_Order (
    product_id int REFERENCES Product(id) ON DELETE CASCADE ,
    order_id int REFERENCES orders(id) ON DELETE SET NULL ,
    PRIMARY KEY(product_id, order_id)
);

CREATE TABLE Comment (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     login varchar(20) NOT NULL,
     text varchar(100) NOT NULL,
     product_id int REFERENCES Product(id) ON DELETE CASCADE
);


